name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    permissions:
       id-token: write
       contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd SIME-web-dashboard
          npm install

      - name: Build app
        run: |
          cd SIME-web-dashboard
          npm run build --prod

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_BEACH_03F13260F }}
          action: "upload"
          app_location: "SIME-web-dashboard"
          output_location: "SIME-web-dashboard/dist/sime-web-dashboard"


